import { chromium } from '@playwright/test';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:390,height:844}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3007/',{waitUntil:'networkidle'});
await page.getByRole('button',{name:'Continue with Google'}).waitFor();
if(await page.getByText('Explore the demo').count())throw new Error('Public demo link is still visible');
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile login layout overflows');
const api=await page.request.get('http://localhost:3007/api/dashboard');
if(api.status()!==401)throw new Error('Unauthenticated API did not return 401: '+api.status());
const demo=await page.request.get('http://localhost:3007/demo');
if(demo.status()!==404)throw new Error('Removed demo route did not return 404: '+demo.status());
if(errors.length)throw new Error('Browser errors: '+errors.join('; '));
console.log('Authenticated-only login, mobile layout, removed demo route, and API auth gate passed.');
await browser.close();