import { chromium } from '@playwright/test';
import fs from 'node:fs';
fs.mkdirSync('.local',{recursive:true});
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3007/demo',{waitUntil:'networkidle'});
await page.screenshot({path:'.local/desktop.png',fullPage:true});
console.log('Title:',await page.title());
console.log('Deep clean summary:',await page.getByRole('heading',{name:'Monday deep-clean summary'}).count());
await page.getByRole('button',{name:'Open my task'}).click();
await page.getByRole('checkbox').first().check();
await page.getByRole('textbox',{name:'Anything to add?'}).fill('Kitchen reset completed.');
await page.getByRole('button',{name:'Save draft',exact:true}).click();
await page.getByText('Draft saved',{exact:true}).waitFor();
await page.getByRole('button',{name:'Close',exact:true}).click();
await page.getByRole('button',{name:'Open my task'}).click();
if(!(await page.getByRole('checkbox').first().isChecked()))throw new Error('Draft tasks were not restored');
const photo=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/WZsAAAAASUVORK5CYII=','base64');
await page.locator('input[type=file][multiple]').setInputFiles({name:'proof.png',mimeType:'image/png',buffer:photo});
await page.getByRole('button',{name:'Submit my clean'}).click();
await page.locator('dialog').waitFor({state:'detached'});
await page.getByRole('button',{name:'Cleaning history'}).click();
await page.getByRole('button',{name:/The daily reset/}).click();
await page.getByRole('button',{name:'Approve',exact:true}).click();
await page.getByRole('button',{name:'Close',exact:true}).click();
console.log('Demo draft, image upload, submit, and admin approval passed.');
await page.getByRole('button',{name:'Our household',exact:true}).click();
console.log('Demo members:',await page.locator('.member-card').count());
await page.getByRole('button',{name:'Overview',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'.local/mobile.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
if(overflow)throw new Error('Mobile layout overflows');
await page.getByRole('button',{name:'Open navigation'}).click();
await page.getByRole('button',{name:'Household QR code'}).click();
await page.locator('.qr-print img').waitFor();
await page.screenshot({path:'.local/qr.png',fullPage:true});
const response=await page.request.get('http://localhost:3007/api/dashboard');
if(response.status()!==401)throw new Error('Unauthenticated API did not return 401: '+response.status());
console.log('Mobile navigation, QR generation, and API auth gate passed.');
console.log('Browser errors:',errors);
if(errors.length)throw new Error('Browser errors present');
await browser.close();
