
import fs from 'node:fs';
function edit(file,from,to){const text=fs.readFileSync(file,'utf8');if(!text.includes(from))throw new Error('Missing edit anchor: '+file+' '+from.slice(0,50));fs.writeFileSync(file,text.replace(from,to));}
edit('lib/demo.ts', "['Deep clean the kitchen', 'Clean bathrooms and toilets', 'Vacuum and mop shared areas', 'Wipe surfaces and empty all bins']", "['Kitchen', 'Oven', 'Stove', 'Toilet', 'Bathroom', 'Common Space', 'Lounge room', 'Laundry']");
edit('app/page.tsx','process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)', 'process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY && process.env.SUPABASE_SECRET_KEY)');
edit('components/dashboard.tsx', "const reload = useCallback", "const openedLink = useRef(false);\n  useEffect(() => { if (!data || openedLink.current) return; const id = new URLSearchParams(window.location.search).get('assignment'); if (id) { const a = data.assignments.find(a => a.id === id); if (a) setSelected(a); } openedLink.current = true; }, [data]);\n  const reload = useCallback");
edit('components/dashboard.tsx', '</section><div className="bottom-note">', '</section><section className="card deep-summary"><div className="section-heading"><div><span className="eyebrow">THE BIGGER CLEAN</span><h2>Monday deep-clean summary</h2><p>{weekly ? formatDate(weekly.date) + " · " + weekly.member_ids.map(id => members.find(m => m.id === id)?.name).join(" & ") : "Eight areas, shared between two people"}</p></div>{weekly && <button className="text-link" onClick={() => setSelected(weekly)}>View clean <ArrowRight size={16} /></button>}</div><div className="area-grid">{(weekly?.tasks || data.settings.weekly_tasks).map((area, i) => { const done = weekly && submissions.some(s => s.assignment_id === weekly.id && ["submitted", "approved"].includes(s.status) && s.tasks.includes(area)); return <div className={done ? "area done" : "area"} key={area}><span>{done ? <Check size={16} /> : String(i + 1).padStart(2, "0")}</span><b>{area}</b><small>{done ? "Submitted" : "To clean"}</small></div>; })}</div></section><div className="bottom-note">');
edit('components/dashboard.tsx', "[loading, setLoading] = useState(!data.demo);", "[loading, setLoading] = useState(!data.demo), [assignees, setAssignees] = useState(a.member_ids), [saved, setSaved] = useState('');");
edit('components/dashboard.tsx', '  async function submit() {', '  async function saveDraft() { setBusy(true); setError(""); setSaved(""); try { if (data.demo) await onChange({ id: own?.id || crypto.randomUUID(), assignment_id: a.id, member_id: data.me.id, tasks, notes, status: own?.status || "draft", submitted_at: own?.submitted_at || null, review_note: own?.review_note || "" }); else { await api(\x60/api/assignments/\x24{a.id}\x60, { method: "POST", body: JSON.stringify({ action: "draft", tasks, notes }) }); await onChange(); } setSaved("Draft saved"); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }\n  async function reassign() { setBusy(true); setError(""); try { if (data.demo) throw new Error("Assignment changes are available in your connected household."); await api("/api/admin", { method: "POST", body: JSON.stringify({ action: "reassign", id: a.id, memberIds: assignees }) }); await onChange(); onClose(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }\n  async function submit() {');
edit('components/dashboard.tsx', '{loading ? <div className="empty-state">', '{data.me.role === "admin" && a.date > data.today && <details className="reassign-panel"><summary>Change who is assigned</summary><div className="reassign-fields">{a.member_ids.map((_, index) => <label key={index}>Housemate {index + 1}<select value={assignees[index]} onChange={e => setAssignees(old => old.map((id, i) => i === index ? e.target.value : id))}>{data.members.map(m => <option value={m.id} key={m.id}>{m.name}</option>)}</select></label>)}</div><button className="button" disabled={busy || data.demo} onClick={reassign}>Save assignment</button></details>}{loading ? <div className="empty-state">');
edit('components/dashboard.tsx','<h3>What did you clean?</h3>','{a.kind === "daily" && <details className="daily-deep-summary"><summary>Deep-clean areas for Monday</summary><div className="area-chips">{data.settings.weekly_tasks.map(area => <span key={area}>{area}</span>)}</div></details>}<h3>What did you clean?</h3>');
edit('components/dashboard.tsx','{error && <p className="error" role="alert">{error}</p>}</div><div className="dialog-footer">','{saved && <p className="success" role="status">{saved}</p>}{error && <p className="error" role="alert">{error}</p>}</div><div className="dialog-footer">');
edit('components/dashboard.tsx','{canEdit && <button className="button primary" disabled={busy || loading', '{canEdit && <button className="button" disabled={busy || loading || a.date > data.today} onClick={saveDraft}>Save draft</button>}{canEdit && <button className="button primary" disabled={busy || loading');
edit('app/api/assignments/[id]/route.ts', "!body.tasks.length||body.tasks.length>30", "(body.action!=='draft'&&!body.tasks.length)||body.tasks.length>30");
edit('app/api/assignments/[id]/route.ts', "db.rpc('submit_clean'", "db.rpc(body.action==='draft'?'save_draft':'submit_clean'");
const photoPath='app/api/assignments/[id]/photos/route.ts';
const photoSource=fs.readFileSync(photoPath,'utf8');
const first=photoSource.indexOf("  const {data:sub,error:subError}");
const last=photoSource.indexOf("  const {error:removeError}",first);
if(first<0||last<0)throw new Error('Photo mutation anchor absent');
fs.writeFileSync(photoPath,photoSource.slice(0,first)+"  const {data:photo,error:retireError}=await db.rpc('retire_photo',{p_assignment:a.id,p_member:member.id,p_photo:photoId});if(retireError)throw new ApiError(retireError.message);\n"+photoSource.slice(last));
const adminPath='app/api/admin/route.ts';
const adminSource=fs.readFileSync(adminPath,'utf8');
const start=adminSource.indexOf("   const {data:sub,error}");
const end=adminSource.indexOf("   return ok({ok:true});",start);
if(start<0||end<0)throw new Error('Review anchor absent');
fs.writeFileSync(adminPath,adminSource.slice(0,start)+"   const {error}=await db.rpc('review_clean',{p_submission:body.id,p_status:body.status,p_note:body.note.trim()});if(error)throw new ApiError(error.message);\n"+adminSource.slice(end));
fs.appendFileSync('app/globals.css', '\n.deep-summary{padding:24px;margin-top:24px}.deep-summary h2{margin-top:7px}.area-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:22px}.area{display:flex;flex-wrap:wrap;align-items:center;gap:10px;padding:15px;border:1px solid var(--line);border-radius:10px}.area>span{font-size:12px;color:#8597b5;background:#f1f5fc;padding:5px 7px;border-radius:6px}.area>b{font-size:13px}.area>small{width:100%;font-size:11px;margin-left:36px}.area.done>span{background:#e8f7ee;color:#278360}.daily-deep-summary,.reassign-panel{padding:13px 15px;border:1px solid var(--line);border-radius:10px;margin:16px 0;font-size:13px}.daily-deep-summary summary,.reassign-panel summary{cursor:pointer;font-weight:600}.area-chips{display:flex;gap:7px;flex-wrap:wrap;margin-top:13px}.area-chips span{background:#f0f4fc;border-radius:5px;padding:5px 9px;font-size:12px}.reassign-fields{display:flex;gap:12px;margin:15px 0}.reassign-fields label{flex:1;min-width:0}@media(max-width:1000px){.area-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.deep-summary{padding:20px 15px}.deep-summary h2{font-size:14px}.deep-summary .text-link{font-size:11px}.area{padding:12px 10px;gap:7px}.area>b{font-size:12px}.dialog-footer{flex-wrap:wrap}.dialog-footer .button{flex:1}}\n');
console.log('Deep-clean summary, draft saving, and admin assignment controls added.');
